name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
      - labelled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/tankwalker/projects/1
          github-token: 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
          #labeled: bug
          #label-operator: OR
