name: Project automation

on:
  workflow_call:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - run: echo "secret ${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/tankwalker/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: ''
          label-operator: OR
