# Jira automation
name: Jira Automation

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      issuetype:
        required: false
        type: string
        default: 'Bug'
      summary:
        required: true
        type: string
        default: ${{ github.event.issue.title }}
      description:
        required: false
        type: string
        default: ${{ github.event.issue.description }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Automation
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create issue
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: ${{ inputs.project }}
        issuetype: ${{ inputs.issuetype }}
        summary: ${{ inputs.summary }}
        description: ${{ inputs.description }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
